### ISSUE TITLE
Container doesn't register on Docker rootless version

### ISSUE THREAD

**Issue by flavienbwk** [osixia/docker-phpLDAPadmin#75]
Hi,

I am using Docker in [rootless mode](https://docs.docker.com/engine/security/rootless/) and encounter a problem with the specific `osixia/phpldapadmin` image.

A `docker pull osixia/phpldapadmin:stable` or any of its version (`:latest`, `:0.9.0` etc...) leads to this error message :

```
latest: Pulling from osixia/phpldapadmin
1ab2bdfe9778: Already exists
0abcaf321aa9: Already exists
6d688c3d4e02: Already exists
454331b99b9a: Pull complete
5cada7c8cb4e: Pull complete
b0f406024ee7: Pull complete
b04a43f9c3ac: Pull complete
92a3a5c2b5a5: Extracting [==================================================>]  34.17kB/34.17kB
e4955dcfbe65: Download complete
failed to register layer: Error processing tar file(exit status 1): failed to mknodChar0UserNS("/container/service/:apache2/install.sh"): failed to mount overlay (lowerdir=/container/service/:apache2/mc0o793276857/l,upperdir=/container/service/:apache2/mc0o793276857/u,workdir=/container/service/:apache2/mc0o793276857/w) on /container/service/:apache2/mc0o793276857/m: no such file or directory
```

Another thing : `osixia/openldap:1.3.0` pulls perfectly fine

Docker version : `19.03.8, build afacb8b7f0`  
OS : Ubuntu 18.04 (bionic)

It works perfectly fine on a classic non-rootless Docker install. Do you have an idea why it fails ?

Thank you for your help.

**Comment by melroy89** [comment]
Try overlay2?

**Comment by Eliav2** [comment]
docker-phpLDAPadmin is based on [osixia/light-baseimage](https://hub.docker.com/r/osixia/light-baseimage) which is based on [phusion/baseimage](https://github.com/phusion/baseimage-docker) which can't run rooless as well...

for evidence: 
```bash
$ docker run --user 1000 --rm -it phusion/baseimage:jammy-1.0.1 
Unable to find image 'phusion/baseimage:jammy-1.0.1' locally
jammy-1.0.1: Pulling from phusion/baseimage
2b55860d4c66: Pull complete
8e058277d049: Pull complete
cac814e1eefd: Pull complete
Digest: sha256:7faf4efcd96870fe090d969703ef8e727cc9de4f465c8442047ffd26f8094e6b
Status: Downloaded newer image for phusion/baseimage:jammy-1.0.1
*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 414, in <module>
    main(args)
  File "/sbin/my_init", line 330, in main
    import_envvars(False, False)
  File "/sbin/my_init", line 90, in import_envvars
    for envfile in listdir("/etc/container_environment"):
  File "/sbin/my_init", line 74, in listdir
    return sorted(os.listdir(path))
PermissionError: [Errno 13] Permission denied: '/etc/container_environment'
```

also see https://github.com/phusion/baseimage-docker/issues/617
