### ISSUE TITLE
What's error:*** CONTAINER_LOG_LEVEL = 5 (trace) *** Run commands before finish... *** Killing all processes...

### ISSUE THREAD

**Issue by zzguang520** [osixia/docker-phpLDAPadmin#77]
Hi team,

    I want to deploy phpldapadmin in cluster, phpldapadmin.yaml as:
kind: ServiceAccount
apiVersion: v1
metadata:
  name:  ldap-sa
---
kind: Deployment
apiVersion: v1
metadata:
  name: ldap-ui
  labels:
    app: ldap-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap-ui
    spec:
      containers:
        - name: ldap-ui
          image: osixia/phpldapadmin:latest
          arg: ['--loglevel','trace']
          env:
            - name: PHPLDAPADMIN_HTTPS
              value: "false"
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: ldap-service.default.svc.cluster.local
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
      serviceAccount: ldap-sa
---
kind: Service
apiVersion: v1
metadata:
  name: ldap-ui-service
spec:
  ports:
    - port: 80
  selector:
    app: ldap-ui

but error in pod logs:
*** CONTAINER_LOG_LEVEL = 5 (trace)
*** Run commands before finish...
*** Killing all processes...

Very simple operation:
1.create namespace 
2.apply -f phpldapadmin.yaml -n namespace

**Comment by zzguang520** [comment]
I have tried to change images: osixia/phpldapadmin:0.7.1

*** CONTAINER_LOG_LEVEL = 5 (trace)
*** Run commands before finish...
*** Killing all processes...
Traceback (most recent call last):
  File "/container/tool/run", line 890, in <module>
    main(args)
  File "/container/tool/run", line 775, in main
    setup_run_directories(args)
  File "/container/tool/run", line 361, in setup_run_directories
    os.makedirs(directory)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/container/run'
